on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, libxml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Mon premier job
        run: echo "Démarrage du jobs"
      - name: Mes premières instructions
        run: ls /
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag demo-app:$(date +%s)

      - name: Start containers
        run: docker-compose up -d
